"""empty message

Revision ID: 6690187a224b
Revises: afe9641146ff
Create Date: 2016-05-25 23:53:00.622946

"""

# revision identifiers, used by Alembic.
revision = '6690187a224b'
down_revision = 'afe9641146ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('name', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'name')
    ### end Alembic commands ###
