"""empty message

Revision ID: a818cfe227d4
Revises: None
Create Date: 2016-04-25 22:48:52.061681

"""

# revision identifiers, used by Alembic.
revision = 'a818cfe227d4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
