"""empty message

Revision ID: afe9641146ff
Revises: None
Create Date: 2016-05-25 17:45:54.414941

"""

# revision identifiers, used by Alembic.
revision = 'afe9641146ff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('devices')
    ### end Alembic commands ###
