"""empty message

Revision ID: d9628bf25888
Revises: c8150e093aa5
Create Date: 2016-05-22 19:13:19.573151

"""

# revision identifiers, used by Alembic.
revision = 'd9628bf25888'
down_revision = 'c8150e093aa5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(u'users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('devices')
    ### end Alembic commands ###
